-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgJ8cLWJM1myaqIVw9
sxQXcXpvfsECx9iG9A7Jth9fLQCgCgYIKoZIzj0DAQehRANCAAT+JcYLWWa9F73D
BjXKiuiLh3zJsKgccSWShjEVTxexPaZmLi/BT7eEH2oQYhUw8SCazWrSQFW0pPv1
gyizArpP
-----END PRIVATE KEY-----