name: inspector
version: 2.0.9+10
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  #get https://pub.dev/packages/get
  get: 4.6.1
  #permission_handler https://pub.dev/packages/permission_handler
  permission_handler: 9.2.0
  #image_picker https://pub.dev/packages/image_picker
  image_picker: 0.8.4+3
  #image_pickers https://pub.dev/packages/image_pickers
  image_pickers: 2.0.0+2
  #image_cropper https://pub.dev/packages/image_cropper
  # image_cropper: ^3.0.0
  #shared_preferences https://pub.dev/packages/shared_preferences
  shared_preferences: 2.0.8
  #connectivity_plus https://pub.dev/packages/connectivity_plus
  connectivity_plus: 2.0.2
  #logger https://pub.dev/packages/logger
  logger: 1.1.0
  #flutter_inappwebview https://pub.dev/packages/flutter_inappwebview
  #webview_flutter: 2.3.0
  flutter_inappwebview: 5.4.3+8
  #dio https://pub.dev/packages/dio
  dio: 4.0.1
  #device_info_plus https://pub.dev/packages/device_info_plus
  device_info_plus: 3.1.1
  #package_info_plus https://pub.dev/packages/package_info_plus
  package_info_plus: 1.3.0
  #fluttertoast https://pub.dev/packages/fluttertoast
  fluttertoast: 8.0.8
  #cached_network_image https://pub.dev/packages/cached_network_image
  cached_network_image: 3.1.0+1
  #pull_to_refresh https://pub.dev/packages/pull_to_refresh
  pull_to_refresh: 2.0.0
  #flutter_spinkit https://pub.dev/packages/flutter_spinkit
  flutter_spinkit: 5.1.0
  #flutter_swiper_null_safety https://pub.dev/packages/flutter_swiper_null_safety
  flutter_swiper_null_safety: 1.0.2
  #flutter_easyloading https://pub.dev/packages/flutter_easyloading
  flutter_easyloading: 3.0.3
  #getwidget https://pub.dev/packages/getwidget
  getwidget: 2.0.5
  #r_upgrade https://pub.dev/packages/r_upgrade
  r_upgrade: 0.3.7+1
  #amap_flutter_map https://pub.dev/packages/amap_flutter_map
#  amap_flutter_map: 3.0.0
  #amap_flutter_location https://pub.dev/packages/amap_flutter_location
  amap_flutter_location: 3.0.0
  #amap_flutter_location https://pub.dev/packages/amap_flutter_search
#  amap_flutter_search: 0.0.4
  #flutter_pickers https://pub.dev/packages/flutter_pickers
  flutter_pickers: 2.1.9
  #date_format https://pub.dev/packages/date_format
  date_format: 2.0.6
  #table_calendar https://pub.dev/packages/table_calendar
  table_calendar: 3.0.5
  #file_picker https://pub.dev/packages/file_picker
  file_picker: 4.5.1
  #common_utils https://pub.dev/packages/common_utils
  common_utils: 2.1.0
  #https://pub.dev/packages/path_provider
  path_provider: 2.0.10
  #https://pub.dev/packages/flutter_braintree
  flutter_braintree: 2.3.1
  #https://pub.dev/packages/tobias
  tobias: 2.4.0+2
  #https://pub.dev/packages/jmessage_flutter
  jmessage_flutter: 2.2.0
  #https://pub.dev/packages/crypto
  crypto: 3.0.2
  #dotted_border https://pub.dev/packages/dotted_border
  dotted_border: 2.0.0+2
  #flutter_slidable https://pub.dev/packages/flutter_slidable
  flutter_slidable: 1.2.1
  #flutter_chat_ui https://pub.dev/packages/flutter_chat_ui
  flutter_chat_ui: 1.5.8
  #url_launcher https://pub.dev/packages/url_launcher
  url_launcher: 6.1.2
  #easy_image_viewer https://pub.dev/packages/easy_image_viewer
  easy_image_viewer: 1.0.4
  #map_launcher https://pub.dev/packages/map_launcher
  map_launcher: 2.2.3
  #flutter_keyboard_visibility https://pub.dev/packages/flutter_keyboard_visibility
  flutter_keyboard_visibility: ^5.4.0
  geolocator: ^7.6.2
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  video_thumbnail: 0.5.0

  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_native_splash: ^1.3.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/3.0x/launch_logo.png"
  ardroid: true
  ios: true
  ios_content_mode: center
  android_gravity: center